### ISSUE TITLE
请求过程一直获取不到数据，请问是什么情况

### ISSUE THREAD

**Issue by Frankie97Liu** [CullenNg/node-spider#1]
打了断点，发现fetchData函数request url之后返回的body是443，不知道哪里有问题

**Comment by Frankie97Liu** [comment]
问题已解决，在fetchData中的headers中加入{'User-Agent': 'request'}模拟用户登录

**Comment by CullenNg** [comment]
@Frankie97Liu  豆瓣会拦截非法请求，一定要设置头信息来请求  👍 :)
